In [2]:
import numpy as np
import time

In [4]:
arr =  np.array([1,2,3,4,5,6])
print(arr, type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [9]:
#python list vs numpy array performance test

size = 1_000_00

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start}")

#numpy array
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end-start}")

python list time = 0.03372669219970703
numpy array time = 0.0013756752014160156


In [10]:
# Memory check
import sys

print(f"python list size = {sys.getsizeof(py_list)* len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 80005600000 bytes
numpy array size = 800000 bytes


In [15]:
#crate from lists

arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)


arr2 =  np.array([1,2,3,4,"Madu"])  #numpy homogenious thats why this array converts into one type 
print(arr2, type(arr2), arr2.dtype, arr2.shape)

#2d array with 2d list
arr3 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,8]])
print(arr3, type(arr3), arr3.dtype, arr3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' 'Madu'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 8]] <class 'numpy.ndarray'> int64 (3, 4)


In [17]:
# creating Arrays
arr1 =  np.zeros((2,3), dtype="int64") #prefill
print(arr1, arr1.shape)

arr2 =  np.ones((2,3), dtype="int64") #prefill
print(arr2, arr2.shape)

arr3 =  np.full((2,3), 100) #prefill with value
print(arr3, arr3.shape)

arr4 =  np.eye(3) #Identity
print(arr4, arr4.shape)

arr5 =  np.arange(1,11,2) #range with value and step
print(arr5, arr5.shape)

arr6 =  np.linspace(1,100,4) #evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [18]:
# Array properties

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
int64
9
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [20]:
#Operations on arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened  = arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [23]:
# Indexing 1D 2D aceess element arr[row][col]

#Fancy Indexing
arr = np.array([1,2,3,4,5])

inx = [1,2,3,4]

print(arr[inx])

#Boolean indexing
print(arr[arr>2])
print(arr[arr%2==0])

[2 3 4 5]
[3 4 5]
[2 4]


In [25]:
# Slicing operation
arr = np.array([1,2,3,4,5])
print(arr[1:4:2])

[2 4]


In [28]:
#slicing a np array just view return kore and list a slicing a copy create kore
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([6,7,8,9,10])
sub_arr = arr[1:3]   ## if we want to copy then use .copy() func
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[7 8]
[200   8]
[  6 200   8   9  10]


In [32]:
# Data types

arr1 = np.array([2+5j])
arr2 = np.array([1+6j])

print(arr1-arr2, arr1.dtype)

arr = np.array(["prime", {1,2,3}, 3.14])
print(arr, arr.dtype)

[1.-1.j] complex128
['prime' {1, 2, 3} 3.14] object


In [3]:
# Multi-dimensional arrays

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_cols = np.sum(arr2D, axis=0)
print(sum_of_cols)

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [8]:
# 3D Array

arr3D = np.array([ [ [1,2],[3,4],[5,6] ] , [ [7,8],[9,10],[11,12] ]  ])  #2 x 3 x 2
print(arr3D, arr3D.shape)

#indexing
print(arr3D[0][1][0]) #print(arr3D[1,1,0])

#slicing
print(arr3D[:, 0, :])

arr3D[:, 0, :] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
3
[[1 2]
 [7 8]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [9]:
# Vectorization --> not need loop for one by one operaation
arr1 = np.array( [1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 + arr2)


[ 7  9 11 13 15]


In [10]:
#Broadcasting --> Auto scale for compatible dimension would equal or one them is 1
arr1 = np.array( [1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [13]:
# Normalize

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean) / std_dev


print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
